# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b66673b181f075553795b216a6cd1785b0f6e2a1f83ac7c644820eb579fdbcb231b9579ae2597c03f5f72f71ac6ce3f4ca48df3c4791b900b129d9010971df91

test:
  secret_key_base: 9d203f63e50de7552ff1eb2714df877f75126ebf713248f85be61125d76979072e16da7d86c40684be206f60bc8a6b9e5216755e87967bcf709c8812f85b964a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
